### ISSUE TITLE
404 authorized(where to set key). 

### ISSUE THREAD

**Issue by jran3228** [wabarc/ipfs-pinner#56]
`	cid, err := infura.PinHash(hash)

		if err != nil {
			panic(err)
		}
`
`Panic in UploadImageHandler handler; 401 Unauthorized`

Is returning authorized 404.  Where do you set the Secret/Project ID?

Thanks!

**Comment by waybackarchiver** [comment]
Thanks you for the reporting!

Infura is still the old gateway, a migration of the dedicated gateways is planned (#39), but there is currently not enough broadband to handle it.

PR is welcome.
